global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'blog-platform'
    static_configs:
      - targets: ['user-service:3002', 'blog-service:3003', 'comment-service:3004']
    metrics_path: '/metrics' 